version: "3.7"

services:

  http:
    image: sbt_image:latest
    networks:
      - ofnet

  locations:
    image: sbt_image:latest
    networks:
      - ofnet

  database:
    image: postgres
    environment:
      POSTGRES_USER: of
      POSTGRES_PASSWORD: of
      POSTGRES_DATABASE: of
      POSTGRES_PORT: 5432
    networks:
      - ofnet

networks:
  ofnet:
