version: "3.7"

services:

  http:
    image: sbt_image:latest
    ports:
      - "9010:8080"
    volumes:
      - ./http:/usr/src
    networks:
      - ofnet

  locations:
    image: sbt_image:latest
    ports:
      - "9020:8080"
    volumes:
      - ./locations:/usr/src
    networks:
      - ofnet

  database:
    image: postgres
    ports:
      - "9030:5432"
    environment:
      POSTGRES_USER: of
      POSTGRES_PASSWORD: of
      POSTGRES_DATABASE: of
      POSTGRES_PORT: 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ofnet

networks:
  ofnet:

volumes:
  db-data:
